---    
- user:
    name: prometheus
    comment: "Prometheus"
    system: yes 
                                          
- name: create prometheus directory structure
  file: >
    state=directory
    path={{ item }}
    owner=prometheus
    group=prometheus
  with_items:
    - "{{ prometheus_root_dir }}"
    - "{{ prometheus_bin_dir }}"
    - "{{ prometheus_dist_dir }}"
    - "{{ prometheus_db_dir }}"

  #- name: create prometheus config directory structure
  #  file: >
  #    state=directory
  #    path={{ prometheus_config_dir }}
  #    owner=root
  #    group=root

- stat: path={{ prometheus_dist_dir }}/prometheus-{{prometheus_version}}.linux-amd64.tar.gz
  register: prometheus_tar_gz

- name: install prometheus and node_exporter from tar.gz
  raw: >
    wget -O {{ prometheus_dist_dir }}/prometheus-{{prometheus_version}}.linux-amd64.tar.gz https://github.com/prometheus/prometheus/releases/download/v{{prometheus_version}}/prometheus-{{prometheus_version}}.linux-amd64.tar.gz;
    tar xvf {{ prometheus_dist_dir }}/prometheus-{{prometheus_version}}.linux-amd64.tar.gz -C {{ prometheus_root_dir }} --strip=1;
  when: prometheus_tar_gz.stat.exists == False
    
- name: create prometheus config file
  template: src=prometheus_netdata.j2 dest={{ prometheus_root_dir }}/prometheus.yml
  # notify: restart prometheus

  #- name: create prometheus default system-wide config
  #  template: src=prometheus_default.j2 dest=/etc/default/prometheus
  #  notify: restart prometheus

- name: Create Prometheus Service in systemd
  template: src=prometheus.service.j2 dest=/etc/systemd/system/prometheus.service
  notify: start prometheus

- name: start prometheus
  service: name=prometheus state=started enabled=yes
